name: dragonfly
services:
  dragonfly:
    container_name: dragonfly
    build:
      context: ./dragonfly
      args:
        - PASSWORD=dragonfly
      network: host
    # network_mode: host
    ports:
      - "3333:22"
      - "8545:8545"
    environment:
      - TZ="Etc/UTC"
    tty: true
    restart: unless-stopped
