#!/bin/bash

# Description: Uses slither-flat to harvest smart contract source code and ABIs from Etherscan for a list of addresses.
# Usage: Set the following enviroment variables and run the script. It will output the flattened source code and ABI for each target contract to the current directory.
#   - ETHERSCAN_API_KEY: Your Etherscan API key for fetching contract ABIs.
#   - TARGETS: A space-separated list of Ethereum contract addresses to harvest (e.g., "0x123 0xabc").
#   - SOLC_VERSION: The version of the Solidity compiler to use (e.g., "0.8.20").
#   - CHAIN_ID: The ID of the Ethereum chain to target (e.g., "1" for Mainnet).

# Get the absolute path of the script's parent directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load required variables from .env file
if [ -f "$SCRIPT_DIR/.env" ]; then
    # Export variables, properly handling spaces in values
    set -a
    source "$SCRIPT_DIR/.env"
    set +a
else
    echo "Error: Config file not found at $SCRIPT_DIR/.env"
    exit 1
fi

# Convert space-separated TARGETS string into a proper BASH array
TARGETS=($TARGETS)

# Verify that required variables are set
if [ -z "$SOLC_VERSION" ] || [ -z "$ETHERSCAN_API_KEY" ] || [ ${#TARGETS[@]} -eq 0 ] || [ -z "$CHAIN_ID" ]; then
    echo "Error: One or more required variables are not set."
    exit 1
else
    echo "Loaded Etherscan API Key: $ETHERSCAN_API_KEY"
    echo "Loaded SOLC: $SOLC_VERSION"
    echo "Loaded Chain ID: $CHAIN_ID"
    echo "Loaded Target List: ${#TARGETS[@]}"
fi

echo "Installing solc version $SOLC_VERSION..."
solc-select install $SOLC_VERSION

# Iterate over the addresses to collect each contract
for ADDRESS in "${TARGETS[@]}"; do
    LOG_PREFIX="[$ADDRESS]:"

    # Trim whitespace from the address loop variable
    ADDRESS=$(echo "$ADDRESS" | xargs)

    ARTIFACT="$SCRIPT_DIR/${ADDRESS}.txt"
    echo "$LOG_PREFIX Generating contract artifact: $ARTIFACT"

    # Collect contract source using slither-flat
    if [ -f "$ARTIFACT" ]; then
        echo "$LOG_PREFIX Contract already collected. Updating..."
        rm -f "$ARTIFACT"
    fi

    # Initialize a temporary directory for the processing of this contract only
    TMP_DIR=$(mktemp -d)
    
    # Enter tmp directory to avoid cluttering the local environment with intermediate files generated by slither-flat
    cd "$TMP_DIR" || exit

    # Fetch contract ABI from Etherscan and save to artifact
    echo "--- START: ABI ---" > "$ARTIFACT"
    ABI_RAW=$(curl -s "https://api.etherscan.io/v2/api?chainid=$CHAIN_ID&module=contract&action=getabi&address=$ADDRESS&apikey=$ETHERSCAN_API_KEY" | jq -r '.result')
    
    # Only pipe through jq formatter if it is valid JSON
    if echo "$ABI_RAW" | jq . >/dev/null 2>&1; then
        echo "$ABI_RAW" | jq . >> "$ARTIFACT"
    else
        echo "$ABI_RAW" >> "$ARTIFACT"
    fi
    echo -e "\n--- END: ABI ---" >> "$ARTIFACT"

    # Download flattened logic and hide compiler warnings
    slither-flat "$ADDRESS" --strategy LocalImport --ignore-compile 2>/dev/null

    # Extract contract source from flattened logic to artifact
    find "$TMP_DIR" -type f -name "*.sol" | while read -r FILE; do
        REL_PATH=${FILE#$TMP_DIR/}
        echo -e "-> Adding File: $REL_PATH"

        {
            echo "--- START: $REL_PATH ---"
            cat "$FILE"
            echo -e "\n--- END: $REL_PATH ---"
        } >> "$ARTIFACT"
    done

    # Exit tmp directory and clean up local environment
    cd "$SCRIPT_DIR" || exit
    rm -rf "$TMP_DIR"

    if [ -f "$ARTIFACT" ]; then
        echo "$LOG_PREFIX Finished extracting contract source to $ARTIFACT (lines: $(wc -l < "$ARTIFACT"))"
    else
        echo "$LOG_PREFIX An error occurred while extracting contract source."
    fi
done

# Print artifacts manifest
echo "All contracts processed:"
for file in "$SCRIPT_DIR"/0x*.txt; do
  echo "- $SCRIPT_DIR/${file##*/}"
done